[33mWARNING[0m:  [03-07-2025 09:36:46] chroma_server_nofile is not supported on Windows. chroma_server_nofile will not be set.
[32mINFO[0m:     [03-07-2025 09:36:48] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [03-07-2025 09:36:48] Starting component System
[36mDEBUG[0m:    [03-07-2025 09:36:48] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [03-07-2025 09:36:48] Starting component SimpleAssignmentPolicy
[36mDEBUG[0m:    [03-07-2025 09:36:48] Starting component SqliteDB
[36mDEBUG[0m:    [03-07-2025 09:37:06] Starting component QuotaEnforcer
[36mDEBUG[0m:    [03-07-2025 09:37:06] Starting component Posthog
[36mDEBUG[0m:    [03-07-2025 09:37:06] Starting component LocalSegmentManager
[36mDEBUG[0m:    [03-07-2025 09:37:06] Starting component SegmentAPI
[32mINFO[0m:     [03-07-2025 09:37:06] Started server process [[36m16792[0m]
[32mINFO[0m:     [03-07-2025 09:37:06] Waiting for application startup.
[32mINFO[0m:     [03-07-2025 09:37:06] Application startup complete.
[32mINFO[0m:     [03-07-2025 09:37:06] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [03-07-2025 09:37:22] ::1:52860 - "GET / HTTP/1.1" 404
[32mINFO[0m:     [03-07-2025 09:37:22] ::1:52860 - "GET /favicon.ico HTTP/1.1" 404
[32mINFO[0m:     [03-07-2025 09:38:25] ::1:52917 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-07-2025 09:38:25] ::1:52917 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[31mERROR[0m:    [03-07-2025 09:40:11] no such column: collections.topic
Traceback (most recent call last):
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\anyio\streams\memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\anyio\streams\memory.py", line 124, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\server\fastapi\__init__.py", line 82, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\base.py", line 154, in call_next
    raise app_exc
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\base.py", line 177, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    raise exc
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\base.py", line 179, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\server\fastapi\__init__.py", line 96, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\base.py", line 154, in call_next
    raise app_exc
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\anyio\_backends\_asyncio.py", line 2461, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\anyio\_backends\_asyncio.py", line 962, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\auth\fastapi.py", line 241, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\server\fastapi\__init__.py", line 415, in create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\api\segment.py", line 167, in create_collection
    coll, created = self._sysdb.create_collection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\db\mixins\sysdb.py", line 209, in create_collection
    existing = self.get_collections(name=name, tenant=tenant, database=database)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hassa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromadb\db\mixins\sysdb.py", line 435, in get_collections
    rows = cur.execute(sql, params).fetchall()
           ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: collections.topic
[32mINFO[0m:     [03-07-2025 09:40:12] ::1:52947 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [03-07-2025 09:43:52] Shutting down
[32mINFO[0m:     [03-07-2025 09:43:52] Waiting for application shutdown.
[36mDEBUG[0m:    [03-07-2025 09:43:52] Stopping component System
[36mDEBUG[0m:    [03-07-2025 09:43:52] Stopping component SegmentAPI
[36mDEBUG[0m:    [03-07-2025 09:43:52] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [03-07-2025 09:43:52] Stopping component Posthog
[36mDEBUG[0m:    [03-07-2025 09:43:52] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [03-07-2025 09:43:52] Stopping component SqliteDB
[36mDEBUG[0m:    [03-07-2025 09:43:52] Stopping component SimpleAssignmentPolicy
[36mDEBUG[0m:    [03-07-2025 09:43:52] Stopping component OpenTelemetryClient
[32mINFO[0m:     [03-07-2025 09:43:52] Application shutdown complete.
[32mINFO[0m:     [03-07-2025 09:43:52] Finished server process [[36m16792[0m]
[33mWARNING[0m:  [03-07-2025 09:44:47] chroma_server_nofile is not supported on Windows. chroma_server_nofile will not be set.
[32mINFO[0m:     [03-07-2025 09:44:47] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [03-07-2025 09:44:47] Starting component System
[36mDEBUG[0m:    [03-07-2025 09:44:47] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [03-07-2025 09:44:47] Starting component SimpleAssignmentPolicy
[36mDEBUG[0m:    [03-07-2025 09:44:47] Starting component SqliteDB
[36mDEBUG[0m:    [03-07-2025 09:44:47] Starting component QuotaEnforcer
[36mDEBUG[0m:    [03-07-2025 09:44:47] Starting component Posthog
[36mDEBUG[0m:    [03-07-2025 09:44:47] Starting component LocalSegmentManager
[36mDEBUG[0m:    [03-07-2025 09:44:47] Starting component SegmentAPI
[32mINFO[0m:     [03-07-2025 09:44:48] Started server process [[36m22524[0m]
[32mINFO[0m:     [03-07-2025 09:44:48] Waiting for application startup.
[32mINFO[0m:     [03-07-2025 09:44:48] Application startup complete.
[32mINFO[0m:     [03-07-2025 09:44:48] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [03-07-2025 09:45:02] ::1:56230 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-07-2025 09:45:02] ::1:56230 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-07-2025 09:45:20] ::1:56253 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[36mDEBUG[0m:    [03-07-2025 09:46:09] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [03-07-2025 09:46:09] ::1:56316 - "POST /api/v1/collections/8bb936b6-ff02-4cbf-b4c6-691dbc318040/query HTTP/1.1" 200
[32mINFO[0m:     [03-07-2025 09:46:20] ::1:56316 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[32mINFO[0m:     [03-07-2025 09:46:20] ::1:56316 - "POST /api/v1/collections/8bb936b6-ff02-4cbf-b4c6-691dbc318040/add HTTP/1.1" 201
